# Generated by Django 3.0.5 on 2024-01-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_wishlistitem'),
        ('CartApp', '0002_wishlist'),
    ]

    operations = [
    ]
