# Generated by Django 3.0.5 on 2024-01-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_auto_20240106_2125'),
        ('CartApp', '0002_auto_20240106_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.User'),
        ),
    ]
