# Generated by Django 3.0.5 on 2024-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0004_auto_20240122_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
