# Generated by Django 3.0.5 on 2024-01-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0002_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
