# Generated by Django 3.0.5 on 2024-01-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0004_auto_20240122_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
