# Generated by Django 3.0.5 on 2024-06-20 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CartApp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_mobile_no', models.CharField(max_length=15)),
                ('billing_address_line1', models.CharField(max_length=255)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_mobile_no', models.CharField(max_length=15)),
                ('shipping_address_line1', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartApp.CartItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentApp.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductsApp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=19)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
