# Generated by Django 3.0.5 on 2024-06-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
