# Generated by Django 4.1.3 on 2024-01-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentApp', '0002_rename_product_item_orderline_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='product',
            new_name='product_item',
        ),
    ]
