# Generated by Django 4.2.7 on 2024-01-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentApp', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
