# Generated by Django 3.0.5 on 2024-06-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0001_initial'),
        ('PaymentApp', '0003_auto_20240620_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CartApp.CartItem'),
        ),
    ]
